# Build docker image

image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build'
          script:
            - cd backend
            - docker-compose -f docker-compose.prod.yml build
          services:
            - docker
