version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5000:5000"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080