name: VyHub Build

on: push

env:
  VUE_APP_KEYWI_API_URL: "https://keywi.agdsn.de/api"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install web dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build web
        working-directory: ./frontend
        run: npm run build

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set correct permissions
        working-directory: ./backend
        run: sudo chmod -R a+rw .

      - name: Build the Docker image
        working-directory: ./backend
        run: docker build -f docker/prod-app.Dockerfile -t ghcr.io/agdsn/keywi:${GITHUB_REF_NAME} .

      - name: Push to Github registry
        run: docker push ghcr.io/agdsn/keywi:${GITHUB_REF_NAME}
