name: VyHub Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set correct permissions
        working-directory: ./backend
        run: sudo chmod -R a+rw .

      - name: Build the Docker image
        working-directory: ./backend
        run: docker build -f docker/prod-app.Dockerfile -t ghcr.io/agdsn/keywi:${GITHUB_REF_NAME} .

      - name: Push to AG DSN registry
        run: docker push ghcr.io/agdsn/keywi:${GITHUB_REF_NAME}
